#!/bin/bash
read N

DEBUG=0

LAYER=5

#SQUARE_7 means 2^(7-LAYER), SQUARE_5 means 2^(5-LAYER), 
SQUARE_7=$[ 2** $[7 - $LAYER]]
SQUARE_6=$[ 2** $[6 - $LAYER]]
SQUARE_5=$[ 2** $[5 - $LAYER]]

#START_x/END_x is the start/end point to print '_' in that line.
#START_1 and END_1 is for sector 1 (rising)
START_1=20
END_1=80
#START_2 and END_2 is for sector 2 (separating)
START_2=19
END_2=81

#OFFSET for sector 2
#'+1' for new line, '0' for entering new LAYER
OFFSET=0    

for ((i=1;i<64;i++))
do
    #first line does not belong to any LAYER
    if [ $i -eq 1 ];then
        for ((j=1;j<101;j++))
        do
            printf "_"
        done
    #sector 1 (rising)
    elif [[ $i -ge $[$SQUARE_7 - $SQUARE_5] ]];then
        TAR_PRINT=$START_1
        for ((j=1;j<101;j++))
        do
            if [ $j -eq $TAR_PRINT ] && [ $j -le $END_1 ] ;then
                if [[ $N -ge $LAYER ]];then  #if (N<LAYER) not need to print
                    printf "1"
                else
                    printf "_"
                fi
                TAR_PRINT=$[$TAR_PRINT + $SQUARE_7]
            else
                printf "_"
            fi
        done
    #sector 2 (separating)
    else
        #judge if it is shift for left or right.
        #DIR=EVEN shift right by OFFSET, DIR=ODD shift left by OFFSET
        DIR=0 
        
        TAR_PRINT=$START_2
        for ((j=1;j<101;j++))
        do
            #if (j == (TAR_PRINT + ((-1)^(DIR) * OFFSET))) && (j<=END_2)
            if [ $j -eq $[$TAR_PRINT + $[ $[-1 ** $DIR] * $OFFSET] ] ] && [ $j -le $END_2 ];then
                if [ $N -ge $LAYER ];then   #if (N<LAYER) not need to print
                    printf "1"
                else
                    printf "_"
                fi
                TAR_PRINT=$[$TAR_PRINT + $SQUARE_6]
                DIR=$[$DIR + 1]
            else
                printf "_"
            fi           
        done
        OFFSET=$[$OFFSET + 1]
    fi
    
    if [[ $i -eq $[$SQUARE_7 - 1] ]];then
        #sector 2
        START_2=$[ $START_2 + $SQUARE_5 ]
        END_2=$[ $END_2 - $SQUARE_5 ]
        OFFSET=0
        #LAYER
        LAYER=$[$LAYER - 1]
        SQUARE_7=$[$SQUARE_7 * 2]
        SQUARE_6=$[$SQUARE_6 * 2]
        SQUARE_5=$[$SQUARE_5 * 2] 
        #sector 1
        START_1=$[ $START_1 + $SQUARE_5 ]
        END_1=$[ $END_1 - $SQUARE_5 ]
        if [ $DEBUG -eq 1 ];then
            printf "Now is LAYER=$LAYER"
            printf ", START_1=$START_1, END_1=$END_1"
            printf ", START_2=$START_2, END_2=$END_2"
        fi
    fi
    
    #next line
    printf "\n"
done
